// Texts for Hebrew/English. Add or edit labels here.
const T={
he:{h:'כותרת',t:'טקסט',q:'שאלה',tb:'טבלה',pdf:'ייצוא PDF',exp:'ייצוא JSON',imp:'ייבוא JSON',ui:'English',
 del:'מחק',dir:'כיוון',auto:'אוטומטי',rtl:'ימין←שמאל',ltr:'שמאל→ימין',row:'+ שורה',col:'+ עמודה',rh:'כותרות לשורות',
 ph:'כתבו כאן...',qph:'כתבו את השאלה...',aph:'תשובה...',title:'כותרת המסמך',saved:'נשמר אוטומטית במכשיר הזה',bad:'קובץ לא תקין',
 c1:'עמודה',fr:'שדות בשורות',pin:'הצג בראש כל עמוד',cancel:'ביטול',sig:'חתימה',sigtitle:'חתמו כאן באצבע',sigclear:'נקה',cancel:'ביטול',sigsave:'שמירה',sigtap:'לחצו לחתימה',fsig:'חתימה',sigall:'חתימה אחרי כל פריט',siglbl:'כיתוב החתימה',tofill:'מצב מילוי',toedit:'מצב עריכה',fcap:'שורה עם כיתוב מתחת',cpl:'כיתוב מתחת לשורה',pfx:'תחילית (לפני השורה)',pb:'התחל בעמוד חדש',pgmin:'לא לפני עמוד',lock:'נעל לעמוד הנוכחי (לא יזוז לעמוד קודם)',pgl:'עמוד',pgest:'חלוקה משוערת, ודאו ב-PDF',wn:'צר',wm:'רגיל',ww:'רחב',ck:'רשימת סימון',ls:'רשימה',addI:'+ פריט',lt:'כותרת הרשימה (למשל דגשים)',snum:'1. 2. 3.',sdot:'• • •',sheb:'א. ב. ג.',fchoice:'בחירה',fill:'מילוי',unit:'יחידה',enc:'ייצוא מוצפן',clr:'נקה מהמכשיר',pw:'בחרו סיסמה להצפנה. שמרו אותה, אי אפשר לשחזר אותה:',pw2:'סיסמה לפתיחת הקובץ:',wrongpw:'סיסמה שגויה',clrq:'למחוק את כל המסמך מהמכשיר הזה? ודאו שייצאתם גיבוי.',ch:'בחירה',ln:'שורות ריקות',opt:'אפשרות',addO:'+ אפשרות',det:'פירוט',dlab:'כותרת הפירוט',o1:'לא',o2:'כן',top:'טקסט עליון (למשל בס"ד)',toptip:'טקסט קטן שיודפס בפינה הימנית העליונה של כל עמוד',pinned:'חוזר בכל עמוד',bsd:'בס"ד בראש כל עמוד',hdr:'שורה שחוזרת בראש כל עמוד',addR:'+ שורה חדשה',delR:'מחק שורה',inRow:'שדות בשורה',addF:'+ שדה',fl:'שם השדה',ftext:'טקסט',fdate:'תאריך',fnumber:'מספר',u:'קו תחתון',corner:'פינה',r1:'שורה'},
en:{h:'Heading',t:'Text',q:'Question',tb:'Table',pdf:'Export PDF',exp:'Export JSON',imp:'Import JSON',ui:'עברית',
 del:'Delete',dir:'Direction',auto:'Auto',rtl:'RTL',ltr:'LTR',row:'+ Row',col:'+ Column',rh:'Row headers',
 ph:'Write here...',qph:'Write the question...',aph:'Answer...',title:'Document title',saved:'Autosaved on this device',bad:'Invalid file',
 c1:'Column',fr:'Field rows',pin:'Repeat at top of every page',cancel:'Cancel',sig:'Signature',sigtitle:'Sign here with your finger',sigclear:'Clear',cancel:'Cancel',sigsave:'Save',sigtap:'Tap to sign',fsig:'Signature',sigall:'Signature after each item',siglbl:'Signature caption',tofill:'Fill mode',toedit:'Edit mode',fcap:'Line with caption below',cpl:'Caption below the line',pfx:'Prefix (before the line)',pb:'Start on a new page',pgmin:'Not before page',lock:'Lock to current page (never moves earlier)',pgl:'Page',pgest:'Estimated page, check in the PDF',wn:'Narrow',wm:'Normal',ww:'Wide',ck:'Checklist',ls:'List',addI:'+ Item',lt:'List title (e.g. Highlights)',snum:'1. 2. 3.',sdot:'• • •',sheb:'א. ב. ג.',fchoice:'Choice',fill:'Fill',unit:'Unit',enc:'Encrypted export',clr:'Clear device',pw:'Choose an encryption password. Keep it, it cannot be recovered:',pw2:'Password to open the file:',wrongpw:'Wrong password',clrq:'Delete the whole document from this device? Make sure you exported a backup.',ch:'Choice',ln:'Blank lines',opt:'Option',addO:'+ Option',det:'Details',dlab:'Details label',o1:'No',o2:'Yes',top:'Top text (e.g. בס"ד)',toptip:'Small text printed at the top-right of every page',pinned:'repeats on every page',bsd:'Add בס"ד at top-right of every page',hdr:'Line repeated at top of every page',addR:'+ New row',delR:'Delete row',inRow:'Fields per row',addF:'+ Field',fl:'Field name',ftext:'Text',fdate:'Date',fnumber:'Number',u:'Underline',corner:'Corner',r1:'Row'}
};